name: Release
on:
  push: { tags: "v[0-9]+.[0-9]+.[0-9]+*" }

permissions: {}
jobs:
  release:
    permissions: { contents: write, id-token: write }
    uses: nodenv/.github/.github/workflows/release.yml@job-summary
    secrets: inherit
